/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SGCompute.CS.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "SGCompute.CS.pb-c.h"
void   sgcompute__cs__piece_info__init
                     (SGCompute__CS__PieceInfo         *message)
{
  static SGCompute__CS__PieceInfo init_value = SGCOMPUTE__CS__PIECE_INFO__INIT;
  *message = init_value;
}
size_t sgcompute__cs__piece_info__get_packed_size
                     (const SGCompute__CS__PieceInfo *message)
{
  assert(message->base.descriptor == &sgcompute__cs__piece_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sgcompute__cs__piece_info__pack
                     (const SGCompute__CS__PieceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sgcompute__cs__piece_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sgcompute__cs__piece_info__pack_to_buffer
                     (const SGCompute__CS__PieceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sgcompute__cs__piece_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SGCompute__CS__PieceInfo *
       sgcompute__cs__piece_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SGCompute__CS__PieceInfo *)
     protobuf_c_message_unpack (&sgcompute__cs__piece_info__descriptor,
                                allocator, len, data);
}
void   sgcompute__cs__piece_info__free_unpacked
                     (SGCompute__CS__PieceInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sgcompute__cs__piece_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sgcompute__cs__compute_info__func_info__init
                     (SGCompute__CS__ComputeInfo__FuncInfo         *message)
{
  static SGCompute__CS__ComputeInfo__FuncInfo init_value = SGCOMPUTE__CS__COMPUTE_INFO__FUNC_INFO__INIT;
  *message = init_value;
}
void   sgcompute__cs__compute_info__formula_info__init
                     (SGCompute__CS__ComputeInfo__FormulaInfo         *message)
{
  static SGCompute__CS__ComputeInfo__FormulaInfo init_value = SGCOMPUTE__CS__COMPUTE_INFO__FORMULA_INFO__INIT;
  *message = init_value;
}
void   sgcompute__cs__compute_info__key_info__key__init
                     (SGCompute__CS__ComputeInfo__KeyInfo__Key         *message)
{
  static SGCompute__CS__ComputeInfo__KeyInfo__Key init_value = SGCOMPUTE__CS__COMPUTE_INFO__KEY_INFO__KEY__INIT;
  *message = init_value;
}
void   sgcompute__cs__compute_info__key_info__init
                     (SGCompute__CS__ComputeInfo__KeyInfo         *message)
{
  static SGCompute__CS__ComputeInfo__KeyInfo init_value = SGCOMPUTE__CS__COMPUTE_INFO__KEY_INFO__INIT;
  *message = init_value;
}
void   sgcompute__cs__compute_info__init
                     (SGCompute__CS__ComputeInfo         *message)
{
  static SGCompute__CS__ComputeInfo init_value = SGCOMPUTE__CS__COMPUTE_INFO__INIT;
  *message = init_value;
}
size_t sgcompute__cs__compute_info__get_packed_size
                     (const SGCompute__CS__ComputeInfo *message)
{
  assert(message->base.descriptor == &sgcompute__cs__compute_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sgcompute__cs__compute_info__pack
                     (const SGCompute__CS__ComputeInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sgcompute__cs__compute_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sgcompute__cs__compute_info__pack_to_buffer
                     (const SGCompute__CS__ComputeInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sgcompute__cs__compute_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SGCompute__CS__ComputeInfo *
       sgcompute__cs__compute_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SGCompute__CS__ComputeInfo *)
     protobuf_c_message_unpack (&sgcompute__cs__compute_info__descriptor,
                                allocator, len, data);
}
void   sgcompute__cs__compute_info__free_unpacked
                     (SGCompute__CS__ComputeInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sgcompute__cs__compute_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sgcompute__cs__result__init
                     (SGCompute__CS__Result         *message)
{
  static SGCompute__CS__Result init_value = SGCOMPUTE__CS__RESULT__INIT;
  *message = init_value;
}
size_t sgcompute__cs__result__get_packed_size
                     (const SGCompute__CS__Result *message)
{
  assert(message->base.descriptor == &sgcompute__cs__result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sgcompute__cs__result__pack
                     (const SGCompute__CS__Result *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sgcompute__cs__result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sgcompute__cs__result__pack_to_buffer
                     (const SGCompute__CS__Result *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sgcompute__cs__result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SGCompute__CS__Result *
       sgcompute__cs__result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SGCompute__CS__Result *)
     protobuf_c_message_unpack (&sgcompute__cs__result__descriptor,
                                allocator, len, data);
}
void   sgcompute__cs__result__free_unpacked
                     (SGCompute__CS__Result *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sgcompute__cs__result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sgcompute__cs__piece_info__field_descriptors[3] =
{
  {
    "describe",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__PieceInfo, describe),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__PieceInfo, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keyDimesion",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SGCompute__CS__PieceInfo, n_keydimesion),
    offsetof(SGCompute__CS__PieceInfo, keydimesion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__cs__piece_info__field_indices_by_name[] = {
  0,   /* field[0] = describe */
  2,   /* field[2] = keyDimesion */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange sgcompute__cs__piece_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sgcompute__cs__piece_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.CS.PieceInfo",
  "PieceInfo",
  "SGCompute__CS__PieceInfo",
  "SGCompute.CS",
  sizeof(SGCompute__CS__PieceInfo),
  3,
  sgcompute__cs__piece_info__field_descriptors,
  sgcompute__cs__piece_info__field_indices_by_name,
  1,  sgcompute__cs__piece_info__number_ranges,
  (ProtobufCMessageInit) sgcompute__cs__piece_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgcompute__cs__compute_info__func_info__field_descriptors[3] =
{
  {
    "formula",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo__FuncInfo, formula),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parameter",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo__FuncInfo, parameter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputsType",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo__FuncInfo, inputstype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__cs__compute_info__func_info__field_indices_by_name[] = {
  0,   /* field[0] = formula */
  2,   /* field[2] = inputsType */
  1,   /* field[1] = parameter */
};
static const ProtobufCIntRange sgcompute__cs__compute_info__func_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sgcompute__cs__compute_info__func_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.CS.ComputeInfo.FuncInfo",
  "FuncInfo",
  "SGCompute__CS__ComputeInfo__FuncInfo",
  "SGCompute.CS",
  sizeof(SGCompute__CS__ComputeInfo__FuncInfo),
  3,
  sgcompute__cs__compute_info__func_info__field_descriptors,
  sgcompute__cs__compute_info__func_info__field_indices_by_name,
  1,  sgcompute__cs__compute_info__func_info__number_ranges,
  (ProtobufCMessageInit) sgcompute__cs__compute_info__func_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgcompute__cs__compute_info__formula_info__field_descriptors[2] =
{
  {
    "sConditionFormula",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo__FormulaInfo, sconditionformula),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sVariableInfo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo__FormulaInfo, svariableinfo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__cs__compute_info__formula_info__field_indices_by_name[] = {
  0,   /* field[0] = sConditionFormula */
  1,   /* field[1] = sVariableInfo */
};
static const ProtobufCIntRange sgcompute__cs__compute_info__formula_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sgcompute__cs__compute_info__formula_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.CS.ComputeInfo.FormulaInfo",
  "FormulaInfo",
  "SGCompute__CS__ComputeInfo__FormulaInfo",
  "SGCompute.CS",
  sizeof(SGCompute__CS__ComputeInfo__FormulaInfo),
  2,
  sgcompute__cs__compute_info__formula_info__field_descriptors,
  sgcompute__cs__compute_info__formula_info__field_indices_by_name,
  1,  sgcompute__cs__compute_info__formula_info__number_ranges,
  (ProtobufCMessageInit) sgcompute__cs__compute_info__formula_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgcompute__cs__compute_info__key_info__key__field_descriptors[2] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo__KeyInfo__Key, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo__KeyInfo__Key, pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__cs__compute_info__key_info__key__field_indices_by_name[] = {
  0,   /* field[0] = index */
  1,   /* field[1] = pos */
};
static const ProtobufCIntRange sgcompute__cs__compute_info__key_info__key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sgcompute__cs__compute_info__key_info__key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.CS.ComputeInfo.KeyInfo.Key",
  "Key",
  "SGCompute__CS__ComputeInfo__KeyInfo__Key",
  "SGCompute.CS",
  sizeof(SGCompute__CS__ComputeInfo__KeyInfo__Key),
  2,
  sgcompute__cs__compute_info__key_info__key__field_descriptors,
  sgcompute__cs__compute_info__key_info__key__field_indices_by_name,
  1,  sgcompute__cs__compute_info__key_info__key__number_ranges,
  (ProtobufCMessageInit) sgcompute__cs__compute_info__key_info__key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgcompute__cs__compute_info__key_info__field_descriptors[2] =
{
  {
    "inputKey",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SGCompute__CS__ComputeInfo__KeyInfo, n_inputkey),
    offsetof(SGCompute__CS__ComputeInfo__KeyInfo, inputkey),
    &sgcompute__cs__compute_info__key_info__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outputKey",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SGCompute__CS__ComputeInfo__KeyInfo, n_outputkey),
    offsetof(SGCompute__CS__ComputeInfo__KeyInfo, outputkey),
    &sgcompute__cs__compute_info__key_info__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__cs__compute_info__key_info__field_indices_by_name[] = {
  0,   /* field[0] = inputKey */
  1,   /* field[1] = outputKey */
};
static const ProtobufCIntRange sgcompute__cs__compute_info__key_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sgcompute__cs__compute_info__key_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.CS.ComputeInfo.KeyInfo",
  "KeyInfo",
  "SGCompute__CS__ComputeInfo__KeyInfo",
  "SGCompute.CS",
  sizeof(SGCompute__CS__ComputeInfo__KeyInfo),
  2,
  sgcompute__cs__compute_info__key_info__field_descriptors,
  sgcompute__cs__compute_info__key_info__field_indices_by_name,
  1,  sgcompute__cs__compute_info__key_info__number_ranges,
  (ProtobufCMessageInit) sgcompute__cs__compute_info__key_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgcompute__cs__compute_info__field_descriptors[5] =
{
  {
    "sFuncInfo",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo, sfuncinfo),
    &sgcompute__cs__compute_info__func_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sConditionInfo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo, sconditioninfo),
    &sgcompute__cs__compute_info__formula_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sKeyInfo",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo, skeyinfo),
    &sgcompute__cs__compute_info__key_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputPieceDescribe",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo, inputpiecedescribe),
    &sgcompute__cs__piece_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outputPieceDescribe",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__ComputeInfo, outputpiecedescribe),
    &sgcompute__cs__piece_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__cs__compute_info__field_indices_by_name[] = {
  3,   /* field[3] = inputPieceDescribe */
  4,   /* field[4] = outputPieceDescribe */
  1,   /* field[1] = sConditionInfo */
  0,   /* field[0] = sFuncInfo */
  2,   /* field[2] = sKeyInfo */
};
static const ProtobufCIntRange sgcompute__cs__compute_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sgcompute__cs__compute_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.CS.ComputeInfo",
  "ComputeInfo",
  "SGCompute__CS__ComputeInfo",
  "SGCompute.CS",
  sizeof(SGCompute__CS__ComputeInfo),
  5,
  sgcompute__cs__compute_info__field_descriptors,
  sgcompute__cs__compute_info__field_indices_by_name,
  1,  sgcompute__cs__compute_info__number_ranges,
  (ProtobufCMessageInit) sgcompute__cs__compute_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue sgcompute__cs__result__status_code__enum_values_by_number[2] =
{
  { "SUCCESS", "SGCOMPUTE__CS__RESULT__STATUS_CODE__SUCCESS", 0 },
  { "FAIL", "SGCOMPUTE__CS__RESULT__STATUS_CODE__FAIL", 1 },
};
static const ProtobufCIntRange sgcompute__cs__result__status_code__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex sgcompute__cs__result__status_code__enum_values_by_name[2] =
{
  { "FAIL", 1 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor sgcompute__cs__result__status_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SGCompute.CS.Result.StatusCode",
  "StatusCode",
  "SGCompute__CS__Result__StatusCode",
  "SGCompute.CS",
  2,
  sgcompute__cs__result__status_code__enum_values_by_number,
  2,
  sgcompute__cs__result__status_code__enum_values_by_name,
  1,
  sgcompute__cs__result__status_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sgcompute__cs__result__field_descriptors[1] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SGCompute__CS__Result, code),
    &sgcompute__cs__result__status_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__cs__result__field_indices_by_name[] = {
  0,   /* field[0] = code */
};
static const ProtobufCIntRange sgcompute__cs__result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sgcompute__cs__result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.CS.Result",
  "Result",
  "SGCompute__CS__Result",
  "SGCompute.CS",
  sizeof(SGCompute__CS__Result),
  1,
  sgcompute__cs__result__field_descriptors,
  sgcompute__cs__result__field_indices_by_name,
  1,  sgcompute__cs__result__number_ranges,
  (ProtobufCMessageInit) sgcompute__cs__result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor sgcompute__cs__compute_server__method_descriptors[2] =
{
  { "ByInfo", &sgcompute__cs__compute_info__descriptor, &sgcompute__cs__result__descriptor },
  { "Create", &sgcompute__cs__piece_info__descriptor, &sgcompute__cs__result__descriptor },
};
const unsigned sgcompute__cs__compute_server__method_indices_by_name[] = {
  0,        /* ByInfo */
  1         /* Create */
};
const ProtobufCServiceDescriptor sgcompute__cs__compute_server__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "SGCompute.CS.ComputeServer",
  "ComputeServer",
  "SGCompute__CS__ComputeServer",
  "SGCompute.CS",
  2,
  sgcompute__cs__compute_server__method_descriptors,
  sgcompute__cs__compute_server__method_indices_by_name
};
void sgcompute__cs__compute_server__by_info(ProtobufCService *service,
                                            const SGCompute__CS__ComputeInfo *input,
                                            SGCompute__CS__Result_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &sgcompute__cs__compute_server__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void sgcompute__cs__compute_server__create(ProtobufCService *service,
                                           const SGCompute__CS__PieceInfo *input,
                                           SGCompute__CS__Result_Closure closure,
                                           void *closure_data)
{
  assert(service->descriptor == &sgcompute__cs__compute_server__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void sgcompute__cs__compute_server__init (SGCompute__CS__ComputeServer_Service *service,
                                          SGCompute__CS__ComputeServer_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &sgcompute__cs__compute_server__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
