/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SGCompute.SR.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "SGCompute.SR.pb-c.h"
void   sgcompute__sr__run_info__key__init
                     (SGCompute__SR__RunInfo__Key         *message)
{
  static SGCompute__SR__RunInfo__Key init_value = SGCOMPUTE__SR__RUN_INFO__KEY__INIT;
  *message = init_value;
}
void   sgcompute__sr__run_info__init
                     (SGCompute__SR__RunInfo         *message)
{
  static SGCompute__SR__RunInfo init_value = SGCOMPUTE__SR__RUN_INFO__INIT;
  *message = init_value;
}
size_t sgcompute__sr__run_info__get_packed_size
                     (const SGCompute__SR__RunInfo *message)
{
  assert(message->base.descriptor == &sgcompute__sr__run_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sgcompute__sr__run_info__pack
                     (const SGCompute__SR__RunInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sgcompute__sr__run_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sgcompute__sr__run_info__pack_to_buffer
                     (const SGCompute__SR__RunInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sgcompute__sr__run_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SGCompute__SR__RunInfo *
       sgcompute__sr__run_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SGCompute__SR__RunInfo *)
     protobuf_c_message_unpack (&sgcompute__sr__run_info__descriptor,
                                allocator, len, data);
}
void   sgcompute__sr__run_info__free_unpacked
                     (SGCompute__SR__RunInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sgcompute__sr__run_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sgcompute__sr__compute__func_info__init
                     (SGCompute__SR__Compute__FuncInfo         *message)
{
  static SGCompute__SR__Compute__FuncInfo init_value = SGCOMPUTE__SR__COMPUTE__FUNC_INFO__INIT;
  *message = init_value;
}
void   sgcompute__sr__compute__init
                     (SGCompute__SR__Compute         *message)
{
  static SGCompute__SR__Compute init_value = SGCOMPUTE__SR__COMPUTE__INIT;
  *message = init_value;
}
size_t sgcompute__sr__compute__get_packed_size
                     (const SGCompute__SR__Compute *message)
{
  assert(message->base.descriptor == &sgcompute__sr__compute__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sgcompute__sr__compute__pack
                     (const SGCompute__SR__Compute *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sgcompute__sr__compute__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sgcompute__sr__compute__pack_to_buffer
                     (const SGCompute__SR__Compute *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sgcompute__sr__compute__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SGCompute__SR__Compute *
       sgcompute__sr__compute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SGCompute__SR__Compute *)
     protobuf_c_message_unpack (&sgcompute__sr__compute__descriptor,
                                allocator, len, data);
}
void   sgcompute__sr__compute__free_unpacked
                     (SGCompute__SR__Compute *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sgcompute__sr__compute__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sgcompute__sr__receive_result__init
                     (SGCompute__SR__ReceiveResult         *message)
{
  static SGCompute__SR__ReceiveResult init_value = SGCOMPUTE__SR__RECEIVE_RESULT__INIT;
  *message = init_value;
}
size_t sgcompute__sr__receive_result__get_packed_size
                     (const SGCompute__SR__ReceiveResult *message)
{
  assert(message->base.descriptor == &sgcompute__sr__receive_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sgcompute__sr__receive_result__pack
                     (const SGCompute__SR__ReceiveResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sgcompute__sr__receive_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sgcompute__sr__receive_result__pack_to_buffer
                     (const SGCompute__SR__ReceiveResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sgcompute__sr__receive_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SGCompute__SR__ReceiveResult *
       sgcompute__sr__receive_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SGCompute__SR__ReceiveResult *)
     protobuf_c_message_unpack (&sgcompute__sr__receive_result__descriptor,
                                allocator, len, data);
}
void   sgcompute__sr__receive_result__free_unpacked
                     (SGCompute__SR__ReceiveResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sgcompute__sr__receive_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sgcompute__sr__run_result__init
                     (SGCompute__SR__RunResult         *message)
{
  static SGCompute__SR__RunResult init_value = SGCOMPUTE__SR__RUN_RESULT__INIT;
  *message = init_value;
}
size_t sgcompute__sr__run_result__get_packed_size
                     (const SGCompute__SR__RunResult *message)
{
  assert(message->base.descriptor == &sgcompute__sr__run_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sgcompute__sr__run_result__pack
                     (const SGCompute__SR__RunResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sgcompute__sr__run_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sgcompute__sr__run_result__pack_to_buffer
                     (const SGCompute__SR__RunResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sgcompute__sr__run_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SGCompute__SR__RunResult *
       sgcompute__sr__run_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SGCompute__SR__RunResult *)
     protobuf_c_message_unpack (&sgcompute__sr__run_result__descriptor,
                                allocator, len, data);
}
void   sgcompute__sr__run_result__free_unpacked
                     (SGCompute__SR__RunResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sgcompute__sr__run_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sgcompute__sr__run_info__key__field_descriptors[3] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__RunInfo__Key, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__RunInfo__Key, pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__RunInfo__Key, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__sr__run_info__key__field_indices_by_name[] = {
  0,   /* field[0] = index */
  2,   /* field[2] = key */
  1,   /* field[1] = pos */
};
static const ProtobufCIntRange sgcompute__sr__run_info__key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sgcompute__sr__run_info__key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.SR.RunInfo.Key",
  "Key",
  "SGCompute__SR__RunInfo__Key",
  "SGCompute.SR",
  sizeof(SGCompute__SR__RunInfo__Key),
  3,
  sgcompute__sr__run_info__key__field_descriptors,
  sgcompute__sr__run_info__key__field_indices_by_name,
  1,  sgcompute__sr__run_info__key__number_ranges,
  (ProtobufCMessageInit) sgcompute__sr__run_info__key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgcompute__sr__run_info__field_descriptors[4] =
{
  {
    "inputKey",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SGCompute__SR__RunInfo, n_inputkey),
    offsetof(SGCompute__SR__RunInfo, inputkey),
    &sgcompute__sr__run_info__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outputKey",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SGCompute__SR__RunInfo, n_outputkey),
    offsetof(SGCompute__SR__RunInfo, outputkey),
    &sgcompute__sr__run_info__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputPieceDescribe",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__RunInfo, inputpiecedescribe),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outputPieceDescribe",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__RunInfo, outputpiecedescribe),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__sr__run_info__field_indices_by_name[] = {
  0,   /* field[0] = inputKey */
  2,   /* field[2] = inputPieceDescribe */
  1,   /* field[1] = outputKey */
  3,   /* field[3] = outputPieceDescribe */
};
static const ProtobufCIntRange sgcompute__sr__run_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sgcompute__sr__run_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.SR.RunInfo",
  "RunInfo",
  "SGCompute__SR__RunInfo",
  "SGCompute.SR",
  sizeof(SGCompute__SR__RunInfo),
  4,
  sgcompute__sr__run_info__field_descriptors,
  sgcompute__sr__run_info__field_indices_by_name,
  1,  sgcompute__sr__run_info__number_ranges,
  (ProtobufCMessageInit) sgcompute__sr__run_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgcompute__sr__compute__func_info__field_descriptors[3] =
{
  {
    "formula",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__Compute__FuncInfo, formula),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parameter",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__Compute__FuncInfo, parameter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputsType",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__Compute__FuncInfo, inputstype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__sr__compute__func_info__field_indices_by_name[] = {
  0,   /* field[0] = formula */
  2,   /* field[2] = inputsType */
  1,   /* field[1] = parameter */
};
static const ProtobufCIntRange sgcompute__sr__compute__func_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sgcompute__sr__compute__func_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.SR.Compute.FuncInfo",
  "FuncInfo",
  "SGCompute__SR__Compute__FuncInfo",
  "SGCompute.SR",
  sizeof(SGCompute__SR__Compute__FuncInfo),
  3,
  sgcompute__sr__compute__func_info__field_descriptors,
  sgcompute__sr__compute__func_info__field_indices_by_name,
  1,  sgcompute__sr__compute__func_info__number_ranges,
  (ProtobufCMessageInit) sgcompute__sr__compute__func_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgcompute__sr__compute__field_descriptors[2] =
{
  {
    "sFuncInfo",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__Compute, sfuncinfo),
    &sgcompute__sr__compute__func_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sRunInfo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__Compute, sruninfo),
    &sgcompute__sr__run_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__sr__compute__field_indices_by_name[] = {
  0,   /* field[0] = sFuncInfo */
  1,   /* field[1] = sRunInfo */
};
static const ProtobufCIntRange sgcompute__sr__compute__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sgcompute__sr__compute__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.SR.Compute",
  "Compute",
  "SGCompute__SR__Compute",
  "SGCompute.SR",
  sizeof(SGCompute__SR__Compute),
  2,
  sgcompute__sr__compute__field_descriptors,
  sgcompute__sr__compute__field_indices_by_name,
  1,  sgcompute__sr__compute__number_ranges,
  (ProtobufCMessageInit) sgcompute__sr__compute__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgcompute__sr__receive_result__field_descriptors[1] =
{
  {
    "errorCode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__ReceiveResult, errorcode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__sr__receive_result__field_indices_by_name[] = {
  0,   /* field[0] = errorCode */
};
static const ProtobufCIntRange sgcompute__sr__receive_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sgcompute__sr__receive_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.SR.ReceiveResult",
  "ReceiveResult",
  "SGCompute__SR__ReceiveResult",
  "SGCompute.SR",
  sizeof(SGCompute__SR__ReceiveResult),
  1,
  sgcompute__sr__receive_result__field_descriptors,
  sgcompute__sr__receive_result__field_indices_by_name,
  1,  sgcompute__sr__receive_result__number_ranges,
  (ProtobufCMessageInit) sgcompute__sr__receive_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgcompute__sr__run_result__field_descriptors[2] =
{
  {
    "runInfo",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__RunResult, runinfo),
    &sgcompute__sr__run_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errorCode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SGCompute__SR__RunResult, errorcode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgcompute__sr__run_result__field_indices_by_name[] = {
  1,   /* field[1] = errorCode */
  0,   /* field[0] = runInfo */
};
static const ProtobufCIntRange sgcompute__sr__run_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sgcompute__sr__run_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGCompute.SR.RunResult",
  "RunResult",
  "SGCompute__SR__RunResult",
  "SGCompute.SR",
  sizeof(SGCompute__SR__RunResult),
  2,
  sgcompute__sr__run_result__field_descriptors,
  sgcompute__sr__run_result__field_indices_by_name,
  1,  sgcompute__sr__run_result__number_ranges,
  (ProtobufCMessageInit) sgcompute__sr__run_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor sgcompute__sr__compute_responser__method_descriptors[1] =
{
  { "ByInfo", &sgcompute__sr__compute__descriptor, &sgcompute__sr__receive_result__descriptor },
};
const unsigned sgcompute__sr__compute_responser__method_indices_by_name[] = {
  0         /* ByInfo */
};
const ProtobufCServiceDescriptor sgcompute__sr__compute_responser__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "SGCompute.SR.ComputeResponser",
  "ComputeResponser",
  "SGCompute__SR__ComputeResponser",
  "SGCompute.SR",
  1,
  sgcompute__sr__compute_responser__method_descriptors,
  sgcompute__sr__compute_responser__method_indices_by_name
};
void sgcompute__sr__compute_responser__by_info(ProtobufCService *service,
                                               const SGCompute__SR__Compute *input,
                                               SGCompute__SR__ReceiveResult_Closure closure,
                                               void *closure_data)
{
  assert(service->descriptor == &sgcompute__sr__compute_responser__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void sgcompute__sr__compute_responser__init (SGCompute__SR__ComputeResponser_Service *service,
                                             SGCompute__SR__ComputeResponser_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &sgcompute__sr__compute_responser__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
static const ProtobufCMethodDescriptor sgcompute__sr__compute_server_waiter__method_descriptors[1] =
{
  { "ByResult", &sgcompute__sr__run_result__descriptor, &sgcompute__sr__receive_result__descriptor },
};
const unsigned sgcompute__sr__compute_server_waiter__method_indices_by_name[] = {
  0         /* ByResult */
};
const ProtobufCServiceDescriptor sgcompute__sr__compute_server_waiter__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "SGCompute.SR.ComputeServerWaiter",
  "ComputeServerWaiter",
  "SGCompute__SR__ComputeServerWaiter",
  "SGCompute.SR",
  1,
  sgcompute__sr__compute_server_waiter__method_descriptors,
  sgcompute__sr__compute_server_waiter__method_indices_by_name
};
void sgcompute__sr__compute_server_waiter__by_result(ProtobufCService *service,
                                                     const SGCompute__SR__RunResult *input,
                                                     SGCompute__SR__ReceiveResult_Closure closure,
                                                     void *closure_data)
{
  assert(service->descriptor == &sgcompute__sr__compute_server_waiter__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void sgcompute__sr__compute_server_waiter__init (SGCompute__SR__ComputeServerWaiter_Service *service,
                                                 SGCompute__SR__ComputeServerWaiter_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &sgcompute__sr__compute_server_waiter__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
